### ISSUE TITLE
GCP has old version of joda-time

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gcp#3]
GATE depends on joda-time version 2.9.2, heritrix-commons depends on version 1.6, Maven's conflict resolution algorithm picks the dependency closer to the root of the tree rather than necessarily the latest one, so `gcp-impl` version 3.0 is getting the old one (which breaks, among other things, the `format-twitter` plugin).

**Comment by ianroberts** [comment]
Fixed on master in 22b8037b620419a41c98eb05a482d5e1b32bc726

**Comment by greenwoodma** [comment]
Seems this was fixed ages ago but github didn't automatically close the issue based on the commit message, so manually closing it now to avoid us getting confused (again)
