### ISSUE TITLE
Batch runner loads wrong version of FastInfoset plugin

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gcp#4]
This still assumes that the FastinfoSet version is tied to the GATE version, so it does not work with GATE 8.5.1 any more.

We should do at least two things:
* Avoid loading if FastInfoset is not requested as output format
* try to figure out a reasonable version if we have to load it

I think, this is really only necessary if the pipeline does not load the plugin itself, so in cases where somebody wants to use a pipeline unchanged and still write fastinfoset (e.g. ANNIE). 
Maybe we should use a separate mechanism to specify the plugin loading by using a parameter that simply provides the full maven coordinates.

**Comment by johann-petrak** [comment]
Remove the pre-loading of the plugin completely, add an option to preload some pipeline instead, that way any number of plugins can get pre-loaded and the GUI can be used to select them.

**Comment by ianroberts** [comment]
> Maybe we should use a separate mechanism to specify the plugin loading by using a parameter that simply provides the full maven coordinates.

This already exists in the latest GCP - see the `-p` option (and `-C` to add an extra local cache).

**Comment by johann-petrak** [comment]
Ah yes, cool, the I guess we can just remove the code that tries to load the plugin and be happy!
